In [ ]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_excel('学生成绩单.xls',header=0)

In [9]:
df = data.drop(['Unnamed: 8','Unnamed: 9'],axis=1)[:68]

In [10]:
df

考号   姓名   语文   数学   英语     总分   班名次 升降幅度
0   70605.0   杨璐  131  143  144  418.0   1.0   ↑4
1   70603.0   王雪  131  135  144  410.0   2.0   ↑1
2   70609.0  韩林霖  127  139  142  408.0   3.0   ↑6
3   70601.0  沙龙逸  123  148  136  407.0   4.0   ↓3
4   70606.0  李鉴学  126  135  140  401.0   5.0   ↑1
..      ...  ...  ...  ...  ...    ...   ...  ...
63  70662.0   赵森   90   29   64  183.0  64.0   ↓2
64  70663.0  满朝升   78   45   47  170.0  65.0   ↓2
65  70658.0  李忠浩   86   32   46  164.0  66.0   ↓8
66  70664.0  侯禹志   75   23   34  132.0  67.0   ↓3
67  70665.0  尹鸿涛   66   23   34  123.0  68.0   ↓3

[68 rows x 8 columns]

In [18]:
total_data = df[['语文','数学','英语']]

In [24]:
total_mean = total_data.mean()
cov = total_data.cov()
total_mean = np.array(total_mean)
cov = np.array(cov)

In [26]:
print(f'语文均值：{total_mean[0]},方差：{df['语文'].var()}')
print(f'数学均值：{total_mean[1]},方差：{df['数学'].var()}')
print(f'英语均值：{total_mean[2]},方差：{df['英语'].var()}')

语文均值：108.0,方差：210.80597014925374
数学均值：102.82352941176471,方差：1115.281826163301
英语均值：109.0,方差：917.4626865671642


In [31]:
print(f'多维高斯模型的均值向量：{total_mean} \n协方差矩阵:\n{cov}')

多维高斯模型的均值向量：[108.0 102.82352941176471 109.0] 
协方差矩阵:
[[ 210.80597015  392.20895522  387.20895522]
 [ 392.20895522 1115.28182616  820.71641791]
 [ 387.20895522  820.71641791  917.46268657]]
